### PR TITLE
Update to 7.3.2, removing sentry.conf.py

### LINKED ISSUE #5: Completely insecure in its current form
This image has hardcoded secret keys with no way to change them, what is the point on having "official images" if they don't even have the most cursory of checks done on them.

It is impossible to securely configure this image.

### LINKED ISSUE #7: Cannot start sentry docker -  SENTRY_URL_PREFIX is not configured
```
# docker logs 8042b...
OperationalError: fe_sendauth: no password supplied

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!! SENTRY_URL_PREFIX is not configured !!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Performing upgrade before service startup...
Syncing...
```

SENTRY_URL_PREFIX is set in sentry.conf.py

### PR DESCRIPTION
**Pull request by tianon**
From now on, "sentry init" is going to be required for generating a sane `sentry.conf.py`.

We can't reasonably keep up with upstream's changes otherwise. :+1:

Replaces https://github.com/docker-library/sentry/pull/4
Closes #2
Closes #5
Closes #7

### CODE REVIEW

**Comment by yosifkit** [comment]
If you have some docs planned, then LGTM.

**Comment by tianon** [comment]
Planned, but nothing written...  We should probably get something written before we totally cut the cord. :disappointed:

**Comment by tianon** [comment]
Especially to make sure we explain how to hook to linked databases after you generate your own config.

**Comment by ramm** [comment]
Still no docs?

I've got some trouble figuring out, how we're supposed to `sentry init` and have it populated with env vars without making my own image.

**Comment by lynchc** [comment]
Really not sure why this is the official image for sentry @ docker hub. There is an awful lot missing on this:
 - Mount a different volume for /home/user/.sentry so that when you run init, it creates a sane config file that you can then modify appropriately.
 - You need postgres and redis. redis isn't optional as it's not only used for caching, it's also used as the celery broker.
 - Also, speaking of celery, you can't just run sentry web, you need to run a separate command that handles the worker proceses. This means that the container needs to have supervisord installed and an appropriate supervisord.conf installed to run both of these. Then the container's start command should be supervisord.

If I get some time, I'll fork this and create a new PR that has all of this in there. including some documentation, which is really critical.

For now, maybe a little blurb on the page that tells people this isn't a functioning image would help.

**Comment by NanneHuiges** [comment]
In regards to celery: is there any way this image works in its current form? As in, can you get the celery workers to run in some way? 

I'm going to try to get this going, but I assume some people might already have changes to get celery running and have some sort of working sentry out of this: if we can add those to this thread it'll probably help the quality? If it comes together we can make a PR out of the seperate parts even?

**Pull request merged**
